### PR TITLE
Update index to check PRs, comments & etc

### PR DESCRIPTION
**Pull request by puneeth579**
**_check completely about PR and comments on PR._**

### CODE REVIEW

**Comment by puneeth579** [comment]
Go through and do approve.

**Comment by puneeth2020** [comment]
can you check on comments again to go live.

**Comment by puneeth579** [comment]
Yes, it is good to go.

**Comment by puneeth2020** [comment]
Great then

**Comment by puneeth2020** [comment]
Sorry, 1 more comment is needed at the end.  Not sufficient to go live.

**Pull request closed without merging**
